const updateProduct = {
  SAVE: "Lưu",
  ALL: "Tất cả",
  ID: "ID",
  STT: "STT",
  CANCEL: "Hủy",
  ADD: "Thêm mới",
  EDIT: "Chỉnh sửa",
  STATUS: "Trạng thái",
  COPPY: "Nhân bản",
  DELETE: "Xóa",
  LOAD: "Nạp",
  BACK_TO_START_PAGE: " Quay lại trang bắt đầu sử dụng",
  PRICE: "Giá mua",
  SELL: "Giá bán",
  UNIT: "Đơn vị",
  YES: "Có",
  NO: "Không",
  ATRIBUTES: "Thuộc tính",
  DESCRIPTION: "Mô tả",
  OTHER: "Khác",
  SINGLE: "Đơn",
  PAIR: "Đôi",
  BARCODE: "Mã vạch",
  ADD_NEW_SUCCESS: "Thêm mới thành công",
  DELETE_SUCCESS: "Xóa thành công",
  UPDATE_SUCCESS: "Cập nhật thành công",
  CONFIRM: "Xác nhận",
  ERROR_OCCURRED_TRY_AGAIN: "Đã có lỗi xảy ra vui lòng thử lại",
  ERROR_OCCURRED_SERVER:
    "Đã xảy ra lỗi trên máy chủ, vui lòng kiểm tra máy chủ.",
  ERROR_BAD_REQUEST: "Đã có lỗi trong yêu cầu được gửi",
  ERROR_REQUIRED: "Vui lòng không bỏ trống dữ liệu dữ liệu",
  ERROR_NOT_FOUND:
    "Yêu cầu được gửi là về một bản ghi không tồn tại và máy chủ không hoạt động",
  PRODUCT: "Hàng hóa",
  BUSINESS_STATUS: "Trạng thái kinh doanh",
  NAME_PRODUCT: "Tên hàng hóa",
  GROUP_PRODUCT: "Nhóm hàng hóa",
  TYPE_PRODUCT: "Loại hàng hóa",
  MANAGER_BY: "Quản lý theo",
  CODE_SKU: "Mã sku",
  IMAGE_PRODUCT: "Ảnh hàng hóa",
  IN_BUSINESS: "Đang kinh doanh",
  OUT_BUSINESS: "Ngừng kinh doanh",
  BOAT_PLATFORM: "Bệt xuồng",
  HOUSEHOLD_GOODS: "Đồ gia dụng",
  DISPLAY_ON_SALES_SCREEN: "Hiển thị lên màn hình bán hàng",
  INFO_ATRIBUTES: "THÔNG TIN THUỘC TÍNH",
  DETAIL_ATRIBUTES: "Chi tiết thuộc tính",
  CODE_SKU_IS_EXSITS: "Đã có mã SKU tồn tại trong hệ thống",
  CODE_SKU_IS_DUPLICATE: "Đã có mã sku trùng nhau vui lòng thử lại",
};
export default updateProduct;
