export const texts = {
  shared: {
    en: {
      save: "Save",
      all: "All",
      cancel: "Cancel",
      add: "Add new",
      edit: "Edit",
      coppy: "Coppy",
      delete: "Delete",
      load: "Load",
      back_to_start_page: "Back to start page",
      price: "Price",
      sell: "Sell",
      unit: "Unit",
      yes: "Yes",
      no: "No",
      atributes: "Atributes",
      description: "Description",
      status: "Status",
      single: "Single",
      pair: "Pair",
      barcode: "Barcode",
      add_new_success: "Add new is successfull",
      update_success: "Update is successfull",
      delete_success: "Delete is successfull",
      confirm: "Confirm",
      error_occurred_please_try_again: "An error occurred please try again",
    },
    vn: {
      save: "Lưu",
      all: "Tất cả",
      cancel: "Hủy",
      add: "Thêm mới",
      edit: "Chỉnh sửa",
      status: "Trạng thái",
      coppy: "Nhân bản",
      delete: "Xóa",
      load: "Nạp",
      back_to_start_page: " Quay lại trang bắt đầu sử dụng",
      price: "Giá mua",
      sell: "Giá bán",
      unit: "Đơn vị",
      yes: "Có",
      no: "Không",
      atributes: "Thuộc tính",
      description: "Mô tả",
      single: "Đơn",
      pair: "Đôi",
      barcode: "Mã vạch",
      add_new_success: "Thêm mới thành công",
      delete_success: "Xóa thành công",
      update_success: "Cập nhật thành công",
      confirm: "Xác nhận",
      error_occurred_please_try_again: "Đã có lỗi xảy ra vui lòng thử lại",
    },
  },
  product: {
    en: {
      product: "Product",
      business_status: "Business status",
      name_product: "Name Product",
      group_product: "Group Product",
      type_product: "Type Product",
      manager_by: "Manager By",
      other: "Other",
      codeSku: "Code sku",
      image_product: "Image Product",
      in_business: "In business",
      out_business: "Out business",
      boat_platform: "Boat platform",
      household_goods: "Household goods",
      display_on_sales_screen: "Display on sales screen",
      info_atributes: "INFOMATION ATRIBUTES",
      detail_atributes: "Detail Atributes",
      code_sku_is_exsists: "Code sku is exsits",
    },
    vn: {
      product: "Hàng hóa",
      business_status: "Trạng thái kinh doanh",
      other: "Khác",
      name_product: "Tên hàng hóa",
      group_product: "Nhóm hàng hóa",
      type_product: "Loại hàng hóa",
      codeSku: "Mã sku",
      image_product: "Ảnh hàng hóa",
      in_business: "Đang kinh doanh",
      out_business: "Ngừng kinh doanh",
      boat_platform: "Bệt xuồng",
      household_goods: "Đồ gia dụng",
      display_on_sales_screen: "Hiển thị lên màn hình bán hàng",
      info_atributes: "THÔNG TIN THUỘC TÍNH",
      detail_atributes: "Chi tiết thuộc tính",
      code_sku_is_exsists: "Mã SKU đã tồn tại",
    },
  },
};

export const getText = (type, lang, key) => {
  return texts[type][lang][key] || key; // Trả về key nếu không tìm thấy
};

export const lang = {
  vn: "vn",
  en: "en",
};
