const actionProduct = {
  SAVE: "Save",
  ID: "ID",
  STT: "STT",
  ALL: "All",
  CANCEL: "Cancel",
  ADD: "Add new",
  EDIT: "Edit",
  COPPY: "Coppy",
  DELETE: "Delete",
  LOAD: "Load",
  BACK_TO_START_PAGE: "Back to start page",
  PRICE: "Price",
  SELL: "Sell",
  UNIT: "Unit",
  YES: "Yes",
  OTHER: "Other",
  NO: "No",
  ATRIBUTES: "Atributes",
  DESCRIPTION: "Description",
  STATUS: "Status",
  SINGLE: "Single",
  PAIR: "Pair",
  BARCODE: "Barcode",
  ADD_NEW_SUCCESS: "Add new is successfull",
  UPDATE_SUCCESS: "Update is successfull",
  DELETE_SUCCESS: "Delete is successfull",
  CONFIRM: "Confirm",
  ERROR_REQUIRED: "Please required",
  ERROR_OCCURRED_TRY_AGAIN: "An error occurred please try again",
  ERROR_OCCURRED_SERVER:
    "An error occurred on the server, please check the server.",
  ERROR_BAD_REQUEST: "There was an error in the request sent.",
  ERROR_NOT_FOUND:
    "The request sent is for a record that does not exist and the server is down.",
  PRODUCT: "Product",
  BUSINESS_STATUS: "Business status",
  NAME_PRODUCT: "Name Product",
  GROUP_PRODUCT: "Group Product",
  TYPE_PRODUCT: "Type Product",
  MANAGER_BY: "Manager By",
  CODE_SKU: "Code sku",
  IMAGE_PRODUCT: "Image Product",
  IN_BUSINESS: "In business",
  OUT_BUSINESS: "Out business",
  BOAT_PLATFORM: "Boat platform",
  HOUSEHOLD_GOODS: "Household goods",
  DISPLAY_ON_SALES_SCREEN: "Display on sales screen",
  INFO_ATRIBUTES: "INFOMATION ATRIBUTES",
  DETAIL_ATRIBUTES: "Detail Atributes",
  CODE_SKU_IS_EXSITS: "Code sku is exsits",
  CODE_SKU_IS_DUPLICATE: "Code sku is duplicate",
};
export default actionProduct;
